### ISSUE TITLE
can we define a variable when using containerless control flow syntax in knockoutjs

### ISSUE THREAD

**Issue by Umar-Mukhtar** [madcapnmckay/Knockout-UI#14]
<script type="text/html" id="ListTemplate">
               (at this point i want to keep the List in a variable to check on the next iteration)
               <li data-bind="if: type  == 'List'">

```
                <input type="checkbox" data-bind="checked: isSelected" />

            <div data-bind="visible: isSelected">
                <a data-bind="text: lastName"></a>
            </div>
        </li>        
        <!-- /ko -->          
    </script>
```

**Comment by madcapnmckay** [comment]
I think this question is for the main [knockout project](https://github.com/knockout/knockout).
